# Generated by Django 4.2.4 on 2023-09-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('ingrediente', models.CharField(max_length=500)),
                ('tipo_de_piel', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='productos/')),
            ],
        ),
    ]
